### PR TITLE
Fix#37

### PR DESCRIPTION
**Pull request by sim2github**
Maybe just return XML without using parse_template+php_execute+cache.
Sitemap not high loaded for caching and information must be fresh as possible.

### CODE REVIEW

**Comment by sim2github** [comment]
- [ ] Fix blog rss

**Comment by sim2github** [comment]
[Not valid batflat feed](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fbatflat.org%2Fblog%2Ffeed%2Fen_english)

**Comment by sim2github** [comment]
Fix #37 
Ready to merge.

**Comment by michu2k** [comment]
Won't fix in this BF version

**Pull request closed without merging**
